#!/bin/sh -ue

fatal() {
    printf %s\\n "$(readlink -f "$0") error: $2" >&2
    exit "$1"
}

section=help
debug_locations=false
user_lang=
user_lang_country=
handle_option() {
    case "$1" in
        debug-locations)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            debug_locations=true
            ;;
        dirs)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            fatal 70 TODO
            ;;
        existing)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            fatal 70 TODO
            ;;
        files)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            fatal 70 TODO
            ;;
        lang)
            [ $# = 2 ] || fatal 64 "missing value for option $1"
            user_lang_country="$2"
            ;;
        missing)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            fatal 70 TODO
            ;;
        section)
            [ $# = 2 ] || fatal 64 "missing value for option $1"
            [ -n "$2" ] || fatal 64 "empty value for option $1"
            section="$2"
            ;;
        *)
            fatal 64 "unknown option: $1"
            ;;
    esac
}

while [ $# -gt 0 ]; do
    case "$1" in
        --)
            shift
            break;;
        --*=*)
            x="${1#--}"
            handle_option "${x%%=*}" "${x#*=}"
            shift;;
        --*)
            handle_option "${1#--}"
            shift;;
        -?*)
            if [ ${#1} = 2 ]; then
                handle_option "${1#-}"
            else
                v="${1#??}"
                x="${1%"$v"}"
                handle_option "${x#-}" "$v"
            fi
            shift;;
        *)
            break;;
    esac
done

check_user_lang_country() {
    user_lang_country="$(printf %s "${user_lang_country%%.*}" | tr A-Z a-z)"
    case "$user_lang_country" in
        [abcdefghijklmnopqrstuvwxyz][abcdefghijklmnopqrstuvwxyz])
            user_lang="$user_lang_country"
            user_lang_country=
            ;;
        [abcdefghijklmnopqrstuvwxyz][abcdefghijklmnopqrstuvwxyz]_[abcdefghijklmnopqrstuvwxyz][abcdefghijklmnopqrstuvwxyz])
            user_lang="${user_lang_country%_*}"
            ;;
        *)
            user_lang=
            user_lang_country=
            return 1
            ;;
    esac
}
if [ -n "$user_lang_country" ]; then
    if [ none = "$user_lang_country" ]; then
        user_lang=
        user_lang_country=
    else
        check_user_lang_country || fatal 64 'invalid --lang value'
    fi
else
    for user_lang_country in "${LC_ALL:-}" "${LC_CTYPE:-}" "${LANG:-}"; do
        if check_user_lang_country; then
            break
        fi
    done
fi


if [ $# -gt 1 ]; then
    fatal 64 'unexpected arguments'
fi
set -- "$(readlink -f "${1:-.}")"
fatal 70 TODO
